[package]
name = "wasdcontroller"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = [
    "consoleapi",
    "libloaderapi",
    "winuser",
] }
backtrace = "0.3"
